Bootstrap: docker
From: condaforge/miniforge3:latest
Stage: condabuild
%files
environments/illumina/environment.yml /environment.yml
environments/extras.yml /extras.yml
%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"
%post

conda env create -f /environment.yml

Bootstrap: docker
From: debian:buster-slim
Stage: final

%post
apt-get update && \
apt-get install -y git procps && \
apt-get clean -y

%files from condabuild
  /opt/conda/envs/artic-ncov2019-illumina /opt/conda/envs/artic-ncov2019-illumina

%environment
export PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH
